name: telegram_bot_tdlib_template
description: A sample command-line application.
homepage: https://youtube.com/@azkadev
repository: https://github.com/azkadev
issue_tracker: https://github.com/azkadev/azkadev
documentation: https://youtube.com/@azkadev
version: 0.0.0
publish_to: none
environment:
  sdk: '>=2.19.4 <3.0.0' 

dependencies:  
  telegram_client: ^0.4.11
  path: ^1.8.2
  galaxeus_lib: ^0.0.63

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  packagex: ^0.0.25