name: telegram_bot_tdlib_template
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.4 <3.0.0' 

dependencies:
  telegram_client: ^0.4.0
  path: ^1.8.3
  galaxeus_lib: ^0.0.61

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  packagex: ^0.0.25