name: app_telegram_template
description: A new Flutter project.
homepage: https://youtube.com/@azkadev
repository: https://github.com/azkadev
issue_tracker: https://github.com/azkadev/azkadev
documentation: https://youtube.com/@azkadev
version: 0.0.0
publish_to: none

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  galaxeus_lib: ^0.0.63
  url_launcher: ^6.1.10
  universal_io: ^2.2.0
  galaxeus_lib_flutter: ^0.0.7
  cool_alert: ^2.0.1
  telegram_client: ^0.4.11
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  path_provider: ^2.0.14

dev_dependencies:
  flutter_lints: ^2.0.0
  packagex: ^0.0.25
  msix: ^3.9.1
  isar_generator: ^3.0.5 
  build_runner: ^2.3.3

  

flutter:
  uses-material-design: true

  assets:    
    - assets/
    - assets/icons/
    
msix_config: 
  display_name: app_telegram_template
  install_certificate: false
  
packagex:
  name: app_telegram_template
  dart_target: app_telegram_template
  flutter_target: main
  dart_name: app_telegram_template
  flutter_name: app_telegram_template
  flutter_commands:
    obfuscate: true
    split-debug-info: 0.0.5
  
