name: app_telegram_template
description: A new Flutter project.
version: 0.0.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  galaxeus_lib: ^0.0.61
  url_launcher: ^6.1.10
  universal_io: ^2.2.0
  galaxeus_lib_flutter: ^0.0.6
  cool_alert: ^2.0.1
  telegram_client: ^0.4.1 
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  packagex: ^0.0.25
  msix: ^3.9.1
  isar_generator: ^3.0.5
  

flutter:
  uses-material-design: true

  assets:    
    - assets/
    - assets/icons/
    
msix_config: 
  display_name: app_telegram_template
  install_certificate: false
  
packagex:
  name: app_telegram_template
  dart_target: app_telegram_template
  flutter_target: main
  dart_name: app_telegram_template
  flutter_name: app_telegram_template
  flutter_commands:
    obfuscate: true
    split-debug-info: 0.0.5
  
