name: telegram_client
description: Telegram Client Lightweight, blazing and Highly customizable for make application telegram based tdlib, mtproto, or bot api and support server side.
version: 0.4.36
homepage: https://youtube.com/@azkadev
repository: https://github.com/azkadev/telegram_client
issue_tracker: https://github.com/azkadev/telegram_client/issues 
documentation: https://telegram-client.vercel.app/
funding:
  - https://github.com/sponsors/azkadev

platforms:
 android:
 ios:
 linux:
 macos:
 web:
 windows:

topics:
  - telegram  
  - tdlib
  - mtproto 
  - userbot
  - telegram-bot-api

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^2.1.0

dependencies:
  ffi: ^2.1.0
  galaxeus_lib: ^0.0.88
  http: ^1.1.0
  path: ^1.8.3
  universal_io: ^2.2.2
  web_ffi: ^0.7.2

executables:
  telegram_client: telegram_client
  tg_cli: telegram_client

screenshots:
  - description: "Telegram Logo"
    path: "assets/telegram.png"