name: telegram_userbot_tdlib_template
description: A Telegram Client.
version: 0.0.0
repository: https://github.com/azkadev/telegram_client.git

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  telegram_client: ^0.3.1023
  path: ^1.8.3
  galaxeus_lib: ^0.0.60

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  packagex: ^0.0.25
  
packagex:
  name: telegram_userbot_tdlib_template
  dart_target: telegram_userbot_tdlib_template
  flutter_target: main
  dart_name: telegram_userbot_tdlib_template
  flutter_name: telegram_userbot_tdlib_template
  is_without_platform_name: false
  flutter_commands:
    obfuscate: true
    split-debug-info: 0.0.5
  

msix_config: 
  display_name: telegram_userbot_tdlib_template
  install_certificate: false
  # publisher_display_name: Azkadev
  # identity_name: org.azkadev.telegram_userbot_tdlib_template
  # msix_version: 0.0.0.0
  # capabilities: internetClient, location, microphone, webcam
