name: telegram_bot_api_template
description: A sample command-line application.
homepage: https://youtube.com/@azkadev
repository: https://github.com/azkadev
issue_tracker: https://github.com/azkadev/azkadev
documentation: https://youtube.com/@azkadev
version: 0.0.0
publish_to: none
funding:
 - https://github.com/azkadev

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  telegram_client: ^0.4.27
  path: ^1.8.3
  galaxeus_lib: ^0.0.73
  alfred: ^1.0.1+2
  supabase_client: ^0.0.19
  xendit: ^0.0.16
  isar: ^3.1.0+1

dev_dependencies:
  lints: ^2.1.0
  test: ^1.21.0
  packagex: ^0.0.28
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.2

packagex:
  name: telegram_bot_api_template
  dart_target: telegram_bot_api_template
  flutter_target: main
  dart_name: telegram_bot_api_template
  flutter_name: telegram_bot_api_template
  is_without_platform_name: false
  flutter_commands:
    obfuscate: true
    split-debug-info: 0.0.5
  

msix_config: 
  display_name: telegram_bot_api_template
  install_certificate: false
  # publisher_display_name: Azkadev
  # identity_name: org.azkadev.telegram_bot_api_template
  # msix_version: 0.0.0.0
  # capabilities: internetClient, location, microphone, webcam
