name: telegram_bot_api_template
description: A sample command-line application.
version: 0.0.0
repository: https://github.com/azkadev/telegram_client.git
publish_to: none
funding:
 - https://github.com/azkadev

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  telegram_client: ^0.4.5
  path: ^1.8.3
  galaxeus_lib: ^0.0.61
  alfred: ^1.0.1+1
  supabase_client: ^0.0.18
  xendit: ^0.0.13
  isar: ^3.0.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  packagex: ^0.0.25
  isar_generator: ^3.0.5
  build_runner: ^2.3.3

packagex:
  name: telegram_bot_api_template
  dart_target: telegram_bot_api_template
  flutter_target: main
  dart_name: telegram_bot_api_template
  flutter_name: telegram_bot_api_template
  is_without_platform_name: false
  flutter_commands:
    obfuscate: true
    split-debug-info: 0.0.5
  

msix_config: 
  display_name: telegram_bot_api_template
  install_certificate: false
  # publisher_display_name: Azkadev
  # identity_name: org.azkadev.telegram_bot_api_template
  # msix_version: 0.0.0.0
  # capabilities: internetClient, location, microphone, webcam
