name: Build Tdlib Linux 
on: [workflow_dispatch]
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Export Release Timestamp
        run: echo "APP_VERSION=v$(date +'%Y.%m.%d.%H.%M.%S')" >> $GITHUB_ENV
      - name: Install Depends
        run: sudo apt-get install -y make git zlib1g-dev libssl-dev gperf cmake clang libc++-dev libc++abi-dev zip
      - uses: actions/checkout@v3
        with:
          repository: tdlib/td
      - name: Compile Tdlib
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build .
      - name: Zip tdlib
        continue-on-error: true
        run: |
          zip "build/libtdjson.so.*"
      - name: Publish Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ github.token }}"
          automatic_release_tag: "latest-tdlib-linux"
          prerelease: false
          title: "Release Tdlib Linux"
          files: |
            build/libtdjson.so.*
