name: Build and Deploy
on: [workflow_dispatch]
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Export Release Timestamp
        run: echo "APP_VERSION=v$(date +'%Y.%m.%d.%H.%M.%S')" >> $GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@v3
 
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.7"
          channel: "stable"
      - name: check dart version
        run: dart --version
      - name: Install Dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt update -y
            sudo apt-get install -y make git zlib1g-dev libssl-dev gperf cmake clang libc++-dev libc++abi-dev php-cli cmake g++
            sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
          fi
          if [ "$RUNNER_OS" == "macOS" ]; then
            brew update
            brew install node
            npm install -g appdmg
          fi
        shell: bash
      - name: Install Dependencies App
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get install -y libmpv-dev mpv webkit2gtk-4.0-dev
          fi
        shell: bash
      - name: Mkdir build
        run: mkdir build
      - name: Set Flutter enable devices
        continue-on-error: true
        run: |
          flutter config --enable-web
          flutter config --enable-linux-desktop
          flutter config --enable-macos-desktop
          flutter config --enable-windows-desktop
          flutter config --enable-android
          flutter config --enable-ios

      - name: Compile Package web
        continue-on-error: true
        shell: bash
        run: |
          cd web
          flutter pub get
          flutter pub run packagex create .
          flutter pub run packagex build web
          if [ "$RUNNER_OS" == "Linux" ]; then
            mv build/packagex/* ./build
          fi
          if [ "$RUNNER_OS" == "Windows" ]; then 
            mv build/packagex/* ./build
          fi
          if [ "$RUNNER_OS" == "macOS" ]; then
            mv build/packagex/* ./build
          fi

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: web/build/web/
